aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Mobile_Post__c.object
<CustomObject>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location Linked to a Building on the AAU Transit System</description>
        <inlineHelpText>Location Linked to a Building on the AAU Transit System</inlineHelpText>
        <label>Location Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Mobile Posts</relationshipLabel>
        <relationshipName>Mobile_Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of the Post/Event</description>
        <inlineHelpText>Category of the Post/Event</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Campus Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Post/Event</description>
        <inlineHelpText>Description of the Post/Event</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_End__c</fullName>
        <description>End Time of the Post/Event</description>
        <inlineHelpText>End Time of the Post/Event</inlineHelpText>
        <label>Event End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start__c</fullName>
        <description>Start Time of the Post/Event</description>
        <inlineHelpText>Start Time of the Post/Event</inlineHelpText>
        <label>Event Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Link_Text__c</fullName>
        <defaultValue>&apos;More Info&apos;</defaultValue>
        <description>The text that will be displayed in the hyperlink for the field &quot;Link__c&quot; in the event detail</description>
        <inlineHelpText>The text that will be displayed in the hyperlink for the field &quot;Link__c&quot; in the event detail</inlineHelpText>
        <label>Link Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <description>Link to site with more information</description>
        <inlineHelpText>Link to site with more information</inlineHelpText>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wellness Series</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the Post/Event</description>
        <inlineHelpText>Title of the Post/Event</inlineHelpText>
        <label>Title</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Post</label>
    <nameField>
        <displayFormat>MP-{0000}</displayFormat>
        <label>Mobile Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_EventsREST_Test.cls
@isTest
private class mob_EventsREST_Test {
	
  static testmethod void testMobilePost() {
    User aaUStudent = mob_TestUtil.makeUser('AAU Student - Platform');
    System.runAs(aaUStudent) {
          Double lat =  37.788008;
          Double longitute = -122.400682;
          Bus_Stop__c busStop = mob_TestUtil.createBusStop('First', lat, longitute);
          
          Mobile_Post__c  mobilePost = new Mobile_Post__c();
          
          mobilePost.Title__c = 'Test Mobile Post';
          mobilePost.Event_Start__c = System.today().addDays(1);
          mobilePost.Event_End__c = System.today().addDays(5);  
          mobilePost.Bus_Stop__c = busStop.id;
          mobilePost.Description__c='Test Mobile Description';
          mobilePost.Category__c ='Campus Recreation';
          mobilePost.Subcategory__c = 'Event';
          mobilePost.Link_Text__c = 'Test Link Text';
          mobilePost.Link__c = 'http://aaurecreationwellness.blogspot.com';
          insert mobilePost; 
        
          mob_EventsREST.getMobileEvents();
    }
  }    

}