aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stops_Routes__c.object
<CustomObject>
    <description>junction for stops and routes</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Order__c</fullName>
        <description>Order of stops. Must be in order when plotted by Gmaps</description>
        <label>Stop Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stops Routes</label>
    <nameField>
        <label>Bus Stops Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_BusStops_Routes_Test.cls
@isTest
private class  mob_BusStops_Routes_Test {
	
	static testmethod void testStudentRest() {
		User aaUStudent = TestUtil.makeUser('AAU Student - Platform');
		System.runAs(aaUStudent) {
			    Bus_Route__c busRoute = TestUtil.createBusRoute('new Test');
			    Double lat =  37.788008;
			    Double longitute = -122.400682;
			    Bus_Stop__c busStop = TestUtil.createBusStop('First', lat, longitute);
			    Bus_Stops_Routes__c busStopRoutes = new Bus_Stops_Routes__c();
			    busStopRoutes.Bus_Route__c = busRoute.Id;
			    busStopRoutes.Bus_Stop__c = busStop.Id;
			    busStopRoutes.Stop_Order__c = 1;
				
				RestRequest req = new RestRequest(); 
    			RestResponse res = new RestResponse();

                // pass the req and resp objects to the method		 
                req.requestURI = 'https://aau--dev6.cs12.my.salesforce.com/services/apexrest/BusStops/';  
                req.httpMethod = 'GET';
    			mob_BusStops_Routes.getBusRoutes(req,res);
		}
	}		
}