aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the stop active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stops_Routes__c.object
<CustomObject>
    <description>junction for stops and routes</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus Stops Routes</label>
    <nameField>
        <label>Bus Stops Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_NextStopLocator.cls
//
//  (c) 2012 Appirio
//
//  
//  Trigger for after insert of Planned Store Object
//  that is created when a portal user submits a request
//
//
//  8/8/2012 - Created



public with sharing class mob_NextStopLocator {
	
	private list<Bus_Stop__c>          allStops          {get;set;}        // List of all Stops in SFDC
	private list<Bus_Stops_Routes__c>  nextStops         {get;set;}        // List of next Stops
	private list<Bus_Stops_Routes__c>  allStopsRoutes    {get;set;}        // List of all Bus_Stops_Routes__c
	private map<String, Bus_Stops_Routes__c> routeMap    {get;set;}        // Map connecting string of Route Name (ex 'A') to Bus_Stop_Routes__c objects
	
	
	
	// Constructor
	public mob_NextStopLocator() {
		allStopsRoutes = [SELECT Bus_Stop__r.Name, Bus_Stop__r.Active__c, Bus_Route__r.Name From Bus_Stops_Routes__c ORDER BY Bus_Stops_Routes__c.Name];
		system.debug('***' + allStopsRoutes[0].Bus_Stop__r.Name);
	}
	
	public list<Bus_Stop__c> getAllBusStops() {
		return allStops;
	}
	
	public list<Bus_Stops_Routes__c> getNextStops(String stopName) {
		return nextStops;
	}

}