aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Mobile_Post__c.object
<CustomObject>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location Linked to a Building on the AAU Transit System</description>
        <inlineHelpText>Location Linked to a Building on the AAU Transit System</inlineHelpText>
        <label>Location Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Mobile Posts</relationshipLabel>
        <relationshipName>Mobile_Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of the Post/Event</description>
        <inlineHelpText>Category of the Post/Event</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Campus Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Post/Event</description>
        <inlineHelpText>Description of the Post/Event</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_End__c</fullName>
        <description>End Time of the Post/Event</description>
        <inlineHelpText>End Time of the Post/Event</inlineHelpText>
        <label>Event End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start__c</fullName>
        <description>Start Time of the Post/Event</description>
        <inlineHelpText>Start Time of the Post/Event</inlineHelpText>
        <label>Event Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Link_Text__c</fullName>
        <defaultValue>&apos;More Info&apos;</defaultValue>
        <description>The text that will be displayed in the hyperlink for the field &quot;Link__c&quot; in the event detail</description>
        <inlineHelpText>The text that will be displayed in the hyperlink for the field &quot;Link__c&quot; in the event detail</inlineHelpText>
        <label>Link Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <description>Link to site with more information</description>
        <inlineHelpText>Link to site with more information</inlineHelpText>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wellness Series</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the Post/Event</description>
        <inlineHelpText>Title of the Post/Event</inlineHelpText>
        <label>Title</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Post</label>
    <nameField>
        <displayFormat>MP-{0000}</displayFormat>
        <label>Mobile Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_EventsREST.cls
@RestResource(urlMapping='/MobileEvents')
global with sharing class mob_EventsREST {
    
    @HttpGet
    global static List<MobileEvent> getMobileEvents() {
        List<MobileEvent> events = new List<MobileEvent>();
        for(Mobile_Post__c event:[SELECT Id,
										Title__c,
										Location__c,
										Bus_Stop__r.Name,
										Category__c,
										Subcategory__c,
										Description__c,
										Event_Start__c,
										Event_End__c,
										Link__c,
										Link_Text__c,
										CreatedDate
									FROM Mobile_Post__c 
									WHERE Event_Start__c >= TODAY 
									ORDER BY Event_Start__c NULLS LAST 
									LIMIT 20]){

            MobileEvent mEvent = new MobileEvent();
            mEvent.id = event.Id;
            mEvent.title = event.Title__c;
            mEvent.category = event.Category__c;
            mEvent.description = event.Description__c;
            mEvent.link = event.Link__c;
            mEvent.createddate = event.CreatedDate;

			//format to show on screen properly if blank
			if(event.Link__c != null && event.Link__c != ''){
				mEvent.linktext = event.Link_Text__c;
			}else{
				mEvent.linktext = '';
			}
			if(event.Subcategory__c != null){
				mEvent.subcategory = event.Subcategory__c;
			}else{
				mEvent.subcategory = '';
			}
			if(event.Location__c != null){
				mEvent.location = event.Location__c;
			}else{
				mEvent.location = '';
			}
			if(event.Bus_Stop__r.Name != null){
				mEvent.locationstop = event.Bus_Stop__r.Name;
			}else{
				mEvent.locationstop = '';
			}
				
			//format for different uses in UX
			if(event.Event_Start__c != null){
				mEvent.startdate = event.Event_Start__c.format('M/d/yy');
				mEvent.starttime = event.Event_Start__c.format('h:mm a');
			}
			if(event.Event_End__c != null){
				mEvent.enddate = event.Event_End__c.format('M/d/yy');
				mEvent.endtime = event.Event_End__c.format('h:mm a');
			}

			//format to show on screen properly if blank
			if(mEvent.startdate == null){ mEvent.startdate = '';}
			if(mEvent.starttime == null){ mEvent.starttime = '';}
			if(mEvent.enddate == null){ mEvent.enddate = '';}
			if(mEvent.endtime == null){ mEvent.endtime = '';}

            events.add(mEvent);
        }
        return events;
    }
    
    global class MobileEvent{
        public String id {get;set;}
        public String title {get;set;}
        public String location {get;set;}
        public String locationstop {get;set;}
        public String category {get;set;}
        public String subcategory {get;set;}
        public String description {get;set;}
        public String startdate {get;set;}
        public String starttime {get;set;}
        public String enddate {get;set;}
        public String endtime {get;set;}
        public String link {get;set;}
        public String linktext {get;set;}
        public Datetime createddate {get;set;}
    }

}