aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the stop active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lat__c</fullName>
        <description>Latitude of the Bus Stop</description>
        <label>Lat</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long__c</fullName>
        <description>Longitude of the Bus Stop</description>
        <label>Long</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Class__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_Nbr__c</fullName>
        <label>Catalog Nbr</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Section__c</fullName>
        <label>Class Section</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Component__c</fullName>
        <description>Short Name of PeopleSoft&apos;s translate value for SSR_COMPONENT</description>
        <label>Course Component</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Psft_Ext_Id__c</fullName>
        <description>Pipe delimited Concatenation of STRM and CLASS_NBR</description>
        <externalId>true</externalId>
        <label>Psft_Ext_Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <referenceTo>ps_Term__c</referenceTo>
        <relationshipName>Class_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ps_Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Class_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Class_Meeting_Number__c</fullName>
        <description>PeopleSoft&apos;s identifier to distinguish meeting patterns for the same class</description>
        <label>Class Meeting Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class_Section__c</fullName>
        <label>Class Section</label>
        <referenceTo>ps_Class__c</referenceTo>
        <relationshipName>Class_Meeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Psft_Ext__c</fullName>
        <externalId>true</externalId>
        <label>Psft_Ext_Id__c</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>ps_Class Meeting</label>
    <nameField>
        <label>Class Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Class Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class Section</label>
        <referenceTo>ps_Class__c</referenceTo>
        <relationshipLabel>ps_Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Psft_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Psft Ext Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>xEnrollments</relationshipLabel>
        <relationshipName>xEnrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ps_Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Term__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Code__c</fullName>
        <description>PeopleSoft&apos;s Term Code</description>
        <externalId>true</externalId>
        <label>Term Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ps_Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/TestUtil.cls
public class TestUtil {
	public static User getUserByUsername(String username) {
		User user = [select Id, Alias, Email, LastName, Profileid
		                  , Username, CommunityNickname, EmailEncodingKey
		                  , LanguageLocaleKey
		             from User 
		             where Username = :username
		            ];
		return user;
	}

	public static User getUserById(ID userId) {
		User user = [select Id, Alias, Email, LastName, Profileid
		                  , Username, CommunityNickname, EmailEncodingKey
		                  , LanguageLocaleKey
		             from User 
		             where Id = :userId
		            ];
		return user;
	}

	public static Contact makeLead(String firstName, String lastName) {
		Contact contact = new Contact(LastName = lastName, FirstName = firstName, Recruiting_Status__c = 'Applicant' );
		insert contact;
		return contact;
	}

	public static Admissions_Opportunity__c makeApplication(Contact lead) {
		return makeApplication(lead, null, 'Undergraduate', null);
	}

	public static Admissions_Opportunity__c makeApplication(Contact lead, String applicationStatus, String career, String unitsEnrolled) {
		Admissions_Opportunity__c application = new Admissions_Opportunity__c(Lead__c = lead.Id, Application_Status__c = applicationStatus, Career__c = career, Current_No_of_Units_Enrolled__c = unitsEnrolled);
		insert application;
		return application;
	}

	public static Program_Plan_SubPlan__c makePlan(Admissions_Opportunity__c application) {
		Program_Plan_SubPlan__c plan = new Program_Plan_SubPlan__c(Admissions_Opportunity__c = application.Id);
		insert plan;
		return plan;
	}

	public static User makeUser(String profileName) {
		return makeUser(profileName, 'Testing', 'en_US', 'America/Los_Angeles');
	}

	public static User makeUser(String profileName, String lastName, String locale, String timezone) {
		Profile profile = [select Id, Name 
		                   from Profile 
		                   where Name = :profileName
		                  ];

		String name = 'test' + Math.random() + '@example.org';

		User user = new User( Alias = 'testuser'
		                    , Email = name
		                    , EmailEncodingKey = 'UTF-8'
		                    , LastName = lastName
		                    , LanguageLocaleKey = locale
		                    , LocalesIdKey = locale
		                    , ProfileId = profile.id
		                    , TimezonesIdKey = timezone
		                    , UserName = name
		                    );
		insert user;

		return user;
	}

    /*
      Methods Added by Virendra for test Classes of AAU Mobile
    */
    public static ps_Term__c createNewTerm(String termCode,String termName){
    	ps_Term__c term = new ps_Term__c();
    	term.Start_Date__c = System.today().addDays(-10);
    	term.End_Date__c = System.today().addDays(10);
    	term.Term_Code__c = termCode;
    	term.name = termName; 
    	insert term;
    	return term;
    }
    
    public static ps_Class__c createClass(String termId,String className,String subject,String CatalogNbr,String section,
                                          String title,String component,String extId){
    	ps_Class__c psClass = new ps_Class__c();
    	psClass.Term__c = termId;
    	psClass.name = className;
    	psClass.Subject__c =  subject;
    	psClass.Catalog_Nbr__c =  CatalogNbr;
    	psClass.Class_Section__c =  section;
    	psClass.Course_Title__c = title;
    	psClass.Course_Component__c=component;
    	psClass.Psft_Ext_Id__c=extId;
    	
    	insert psClass;
    	return psClass;
    }
    
    public static ps_Class_Meeting__c createClassMeeting(String classId,String name,Integer meetingNo,String extId){
    	ps_Class_Meeting__c psClassMeeting = new ps_Class_Meeting__c();
    	psClassMeeting.Class_Section__c = classId;
    	psClassMeeting.Name = name;
    	psClassMeeting.Class_Meeting_Number__c= meetingNo;
    	psClassMeeting.Psft_Ext__c = extId;
    	psClassMeeting.End_Date__c = System.today().addDays(10);
    	psClassMeeting.Start_Date__c = System.today().addDays(10);
    	psClassMeeting.Monday__c = true;
    	psClassMeeting.Wednesday__c = true;
    	psClassMeeting.Friday__c = true;
    	insert psClassMeeting;
    	return psClassMeeting;
    }
    
    public static ps_Enrollment__c createEnrollment(String classId,String name,String studentId){
    	ps_Enrollment__c psEnrollment = new ps_Enrollment__c();
    	psEnrollment.Class_Section__c = classId;
    	psEnrollment.Name = name;
    	psEnrollment.Student__c = studentId;
    	psEnrollment.Enrollment_Status__c = 'E';
    	insert psEnrollment;
    	return psEnrollment;
    }
    
    public static Bus_Route__c createBusRoute(String name){
    	Bus_Route__c busRoute = new Bus_Route__c();
    	busRoute.name = name;
    	insert busRoute;
    	return busRoute;
    }
    
    public static Bus_Stop__c createBusStop(String name,Double lat,Double longitute){
    	Bus_Stop__c busStop = new Bus_Stop__c();
    	busStop.name = name;
    	busStop.Active__c = true;
    	busStop.Lat__c = lat;
    	busStop.Long__c = longitute;
    	insert busStop;
    	return busStop;
    }
    
    
	public static testmethod void testTestUtil() {
		User testUser = TestUtil.makeUser('Standard User');
		testUser = TestUtil.getUserById(testUser.Id);
		testUser = TestUtil.getUserByUsername(testUser.Username);

		Contact lead = TestUtil.makeLead('Marc', 'Benioff');
		Admissions_Opportunity__c application = TestUtil.makeApplication(lead);
	}
	
	
}