aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What order should this stop show in the stop list.</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop_Schedule__c.object
<CustomObject>
    <description>Link between bus route and stop with scheduled time</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Route__c</fullName>
        <description>This is the instance of the Route.  There could be two buses on the route at the same time, but at different places in the route.  This reflect which bus is which</description>
        <inlineHelpText>This is the instance of the Route.  There could be two buses on the route at the same time, but at different places in the route.  This reflect which bus is which</inlineHelpText>
        <label>Sub Route</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Bus Stop Schedule</label>
    <nameField>
        <label>Bus Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stop Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop_Schedule_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules Staging</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules_Staging</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules Staging</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules_Staging</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Route__c</fullName>
        <label>Sub Route</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Bus Stop Schedule Staging</label>
    <nameField>
        <label>Bus Stop Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stop Schedules Staging</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stops_Routes__c.object
<CustomObject>
    <description>junction for stops and routes</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Order__c</fullName>
        <description>Order of stops. Must be in order when plotted by Gmaps</description>
        <label>Stop Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stops Routes</label>
    <nameField>
        <label>Bus Stops Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stops_Routes_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stops Routes Staging</relationshipLabel>
        <relationshipName>Bus_Stops_Routes_Staging</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stops Routes Staging</relationshipLabel>
        <relationshipName>Bus_Stops_Routes_Staging</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Order__c</fullName>
        <label>Stop Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stops Routes Staging</label>
    <nameField>
        <label>Bus Stops Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops Routes Staging</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/Bus_Schedule_Editor_Test.cls
@isTest
private class Bus_Schedule_Editor_Test {

   public static  User sysAdmin;
	public static  Bus_Route__c route;
	public static  Bus_Stop__c stop1;
	public static  Bus_Stop__c stop2;
	public static  Bus_Stops_Routes__c stop1route;
	public static  Bus_Stops_Routes__c stop2route;
	public static  Bus_Stop_Schedule__c stop1Schedule;
	public static  Bus_Stop_Schedule__c stop2Schedule; 
	static{
		sysAdmin = mob_TestUtil.makeUser('System Administrator');
	}
	static testmethod void testScheduleEditor(){
		System.runAs(sysAdmin){
			
			route = mob_TestUtil.createBusRoute('NorthTest');
			stop1 = mob_TestUtil.createBusStop('Stop A', (37.78218800).doubleValue(), (-122.41895900).doubleValue());
			stop2 = mob_TestUtil.createBusStop('Stop B', (37.78238800).doubleValue(), (-122.41895900).doubleValue());
			stop1route = mob_TestUtil.createBusStopRoute(stop1.id, route.id, 0);
			stop2route = mob_TestUtil.createBusStopRoute(stop2.id, route.id, 1);
			stop1Schedule = mob_TestUtil.createBusSchedule(stop1.id, route.id, 0, '1:15PM');
			stop2Schedule = mob_TestUtil.createBusSchedule(stop2.id, route.id, 1, '1:30 PM');
			
				Bus_Schedule_Editor_Controller con = new Bus_Schedule_Editor_Controller();
				List<Bus_Schedule_Editor_Controller.BusStopSchedule> lstSch = Bus_Schedule_Editor_Controller.get_ScheduleData(route.Id,  '0');
				 system.assert(lstSch.size()>0);
				 
				 List<string> str_routestops = new List<string>(); 
		 	 	 str_routestops.add( '{Stop_Order__c=0, Bus_Route__c=' + route.id + ', type=Bus_Stops_Routes_Staging__c, Bus_Stop__c=' + stop1.id + '}');
		 	 	 str_routestops.add( '{Stop_Order__c=1, Bus_Route__c=' + route.id + ', type=Bus_Stops_Routes_Staging__c, Bus_Stop__c=' + stop2.id + '}');

				List<string> str_sch = new List<string>();
				str_sch.add('{Bus_Route__c=' + route.id + ', Time__c=7:10 AM, Sub_Route__c=0, Order__c=0, type=Bus_Stop_Schedule_Staging__c, Bus_Stop__c=' + stop1.id + '}'); 
				str_sch.add('{Bus_Route__c=' + route.id + ', Time__c=7:15 AM, Sub_Route__c=0, Order__c=1, type=Bus_Stop_Schedule_Staging__c, Bus_Stop__c=' + stop2.id + '}');

		 	 	 string res = Bus_Schedule_Editor_Controller.save_ScheduleData( route.id,  '0', str_routestops,str_sch );
		 	 	 system.assert(res=='');
		 	 	 
		 	 	 lstSch = Bus_Schedule_Editor_Controller.get_ScheduleData(route.Id,  '0');
		 	 	system.assert(lstSch.size()>0);
		 	 	
		 	 	 res = Bus_Schedule_Editor_Controller.publish_ScheduleData(route.id, '0');
		 	 	   system.assert(res=='');
		 	 	 
		 	 	  str_routestops = new List<string>();
		 	 	 str_routestops.add( '{Stop_Order__c=0, Bus_Route__c=' + route.id + ', type=Bus_Stops_Routes_Staging__c, Bus_Stop__c=' + stop1.id + '}');
		 	 	 str_routestops.add( '{Stop_Order__c=1, Bus_Route__c=' + route.id + ', type=Bus_Stops_Routes_Staging__c, Bus_Stop__c=' + stop2.id + '}');

				 str_sch = new List<string>();
				str_sch.add('{Bus_Route__c=' + route.id + ', Time__c=7:10 AM, Sub_Route__c=0, Order__c=0, type=Bus_Stop_Schedule_Staging__c, Bus_Stop__c=' + stop1.id + '}'); 
				str_sch.add('{Bus_Route__c=' + route.id + ', Time__c=7:15 AM, Sub_Route__c=0, Order__c=1, type=Bus_Stop_Schedule_Staging__c, Bus_Stop__c=' + stop2.id + '}');
				
		 	 	  res = Bus_Schedule_Editor_Controller.save_ScheduleData( route.id,  '0', str_routestops,str_sch );
		 	 	 system.assert(res=='');
		 	 	  res = Bus_Schedule_Editor_Controller.publish_ScheduleData_All();
		 	 	   system.assert(res=='');
		 	 	
				 List<Bus_Route__c> lst = Bus_Schedule_Editor_Controller.add_Route(  'newTestRoute',  'red', 'red', 'newTestRoute', true, '');
				 system.assert(lst.size()>1);
				 
			
		}
	}
}