aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <fields>
        <fullName>Route_Color__c</fullName>
        <description>The color of the route</description>
        <label>Route Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop_Schedule__c.object
<CustomObject>
    <description>Link between bus route and stop with scheduled time</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stop Schedules</relationshipLabel>
        <relationshipName>Bus_Stop_Schedules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Bus Stop Schedule</label>
    <nameField>
        <label>Bus Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stop Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_BusStop_Schedule.cls
@RestResource(urlMapping='/BusStopSchedule/*')
global with sharing class  mob_BusStop_Schedule {

    @HttpGet
    global static BusStopSchedule getBusStopSchedule(RestRequest req, RestResponse res) {
        String busStopName = EncodingUtil.urlDecode(req.params.get('busStopName'), 'UTF-8');
        BusStopSchedule schedule = new BusStopSchedule();
        system.debug('stop: ' + busStopName);
        Map <String, BusRoute>routes = new Map <String, BusRoute>();
        for(Bus_Stop_Schedule__c busStopSchedule:[Select Time__c, Bus_Stop__r.Name, Bus_Stop__c, Bus_Route__r.Name, Bus_Route__r.Route_Color__c, Bus_Route__c From Bus_Stop_Schedule__c where Bus_Stop__r.Name=:busStopName]){
            
            system.debug('_______' + busStopSchedule.Bus_Stop__r.Name);
            BusRoute currentRoute = routes.get(busStopSchedule.Bus_Route__r.Name);
            system.debug('current route: ' + busStopSchedule.Bus_Route__r.Name);
            if (currentRoute == null){
                currentRoute = new BusRoute();
                currentRoute.name = busStopSchedule.Bus_Route__r.Name;
                currentRoute.color = busStopSchedule.Bus_Route__r.Route_Color__c;
                currentRoute.schedule = new List<String>();
                
                routes.put(busStopSchedule.Bus_Route__r.Name, currentRoute);
            }
            
            currentRoute.schedule.add(busStopSchedule.Time__c);
            
        }
        system.debug('current busStopName: ' + busStopName);
        schedule.stop = busStopName;
        schedule.routes = routes.values();
        return schedule;
    }

    
    
    global class BusStopSchedule {

        global String stop{get;set;}
        global List<BusRoute> routes{get;set;}
        

    }
    
    global class BusRoute {

        global String name{get;set;}
        global String color{get;set;}
        global List <String> schedule{get;set;}
        
        
    }
    
}