aau/sf_autobackup/objects/Bus_Route__c.object
<CustomObject>
    <description>A Bus Route, Collection of Stops</description>
    <fields>
        <fullName>Route_Color__c</fullName>
        <description>The color of the route</description>
        <label>Route Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_Marker__c</fullName>
        <description>The file name of the image marker for this route.</description>
        <inlineHelpText>The file name of the image marker for this route.</inlineHelpText>
        <label>Route Marker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teletrac_Name__c</fullName>
        <description>The unabbreviated name of the Bus Route as returned by Teletrac.</description>
        <inlineHelpText>The unabbreviated name of the Bus Route as returned by Teletrac.</inlineHelpText>
        <label>Teletrac Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the stop active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>High_Fidelity_Waypoint__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this is a preprocessed waypoint only meant for accurately drawing the route on the screen.  If false, it is an actual location that a bus will stop at.</description>
        <inlineHelpText>If true, this is a preprocessed waypoint only meant for accurately drawing the route on the screen.  If false, it is an actual location that a bus will stop at.</inlineHelpText>
        <label>High Fidelity Waypoint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lat__c</fullName>
        <description>Latitude of the Bus Stop</description>
        <label>Lat</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long__c</fullName>
        <description>Longitude of the Bus Stop</description>
        <label>Long</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What order should this stop show in the stop list.</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/Bus_Stops_Routes__c.object
<CustomObject>
    <description>junction for stops and routes</description>
    <fields>
        <fullName>Bus_Route__c</fullName>
        <label>Bus Route</label>
        <referenceTo>Bus_Route__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bus_Stop__c</fullName>
        <label>Bus Stop</label>
        <referenceTo>Bus_Stop__c</referenceTo>
        <relationshipLabel>Bus Stops Routes</relationshipLabel>
        <relationshipName>Bus_Stops_Routes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Order__c</fullName>
        <description>Order of stops. Must be in order when plotted by Gmaps</description>
        <label>Stop Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bus Stops Routes</label>
    <nameField>
        <label>Bus Stops Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_BusStops_Routes.cls
@RestResource(urlMapping='/BusStops/')
global with sharing class  mob_BusStops_Routes {

    @HttpGet
    global static List<BusRoutes> getBusRoutes(RestRequest req, RestResponse res) {
        List<BusRoutes> busRoutes = new List<BusRoutes>();
        String rootName = null;
        Map<String,List<BusStop>> busStopMap = new Map<String,List<BusStop>> (); 
        Map<String,List<BusStop>> busStopHiFi = new Map<String,List<BusStop>>();
        for(Bus_Stops_Routes__c busStopRoutes:[Select  Bus_Stop__r.Long__c, Bus_Stop__r.Lat__c, Bus_Stop__r.High_Fidelity_Waypoint__c,
                                               Bus_Stop__r.Name, Bus_Stop__r.Active__c, Bus_Stop__r.Id, Bus_Stop__r.Order__c,
                                               Bus_Route__r.Name, Bus_Route__r.Route_Color__c, Bus_Route__r.Teletrac_Name__c,
                                               Bus_Route__r.Route_Marker__c, Bus_Route__r.Id
                                               From Bus_Stops_Routes__c where Bus_Route__r.Active__c = true and (Bus_Stop__r.Active__c = true OR Bus_Stop__r.High_Fidelity_Waypoint__c = true) order by Stop_Order__c ]){
            BusStop  stop = new BusStop();
            stop.id = busStopRoutes.Bus_Stop__r.Id;
            stop.stopName =  busStopRoutes.Bus_Stop__r.Name;
            stop.longitude = busStopRoutes.Bus_Stop__r.Long__c;
            stop.latitude =  busStopRoutes.Bus_Stop__r.Lat__c; 
            stop.active = busStopRoutes.Bus_Stop__r.Active__c;
            stop.color = busStopRoutes.Bus_Route__r.Route_Color__c; 
            stop.stopOrder = (Integer)busStopRoutes.Bus_Stop__r.Order__c; 
            stop.routeTeletracName = busStopRoutes.Bus_Route__r.Teletrac_Name__c;
            stop.routeMarker = busStopRoutes.Bus_Route__r.Route_Marker__c;
            BusRoutes routes = new BusRoutes();
            routes.stops = new List<BusStop>(); 
            if(busStopRoutes.Bus_Stop__r.High_Fidelity_Waypoint__c){
	            if(busStopHiFi.containsKey(busStopRoutes.Bus_Route__r.Name)){
	               busStopHiFi.get(busStopRoutes.Bus_Route__r.Name).add(stop);
	            }else{
	               routes.stops = new List<BusStop>();
	               routes.stops.add(stop);
	               busStopHiFi.put(busStopRoutes.Bus_Route__r.Name,routes.stops);    
	            }
            } else{
            	if(busStopMap.containsKey(busStopRoutes.Bus_Route__r.Name)){
	               busStopMap.get(busStopRoutes.Bus_Route__r.Name).add(stop);
	            }else{
	               routes.stops = new List<BusStop>();
	               routes.stops.add(stop);
	               busStopMap.put(busStopRoutes.Bus_Route__r.Name,routes.stops);    
	            }
            }
        }
        if(!busStopMap.isEmpty()){
            for(String key:busStopMap.keySet()){
              BusRoutes routes = new BusRoutes();
              routes.stops = new List<BusStop>();
              routes.highFidelity = new List<BusStop>();
              routes.routeName = key;
              routes.stops = busStopMap.get(key);
              if(busStopHiFi.containsKey(key)){
              	routes.highFidelity = busStopHiFi.get(key);
              }
              busRoutes.add(routes);        
            }
        }
        return busRoutes;
    }
    
    global  class BusRoutes{
        public String routeName{get;set;}
        public List<BusStop> stops{get;set;}
        public List<BusStop> highFidelity{get;set;}
    }
    
    public  class BusStop{
        public String stopName{get;set;}
        public double latitude{get;set;}
        public double longitude{get;set;}
        public Integer stopOrder{get;set;}
        public boolean active{get;set;}
        public String color{get;set;}
        public string id{get;set;}
        public String routeTeletracName{get;set;}
        public String routeMarker{get;set;}
    }
}