aau/sf_autobackup/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link Student User to their Contact to grab Class Schedule, etc.</description>
        <inlineHelpText>Link Student User to their Contact to grab Class Schedule, etc.</inlineHelpText>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

aau/sf_autobackup/objects/ps_Class__c.object
<CustomObject>
    <label>ps_Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Class_Meeting__c.object
<CustomObject>
    <label>ps_Class Meeting</label>
    <nameField>
        <label>Class Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Class Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Enrollment__c.object
<CustomObject>
    <label>ps_Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Term__c.object
<CustomObject>
    <label>ps_Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_ClassMeeting_ChatRest_Test.cls
@isTest
private class mob_ClassMeeting_ChatRest_Test {
	
	public static Contact leadContact;
	public static  User sysAdmin;
	
	static{
		 sysAdmin =  mob_TestUtil.makeUser('System Administrator');
    	 leadContact = new Contact(LastName = 'lName', FirstName = 'fName',student_user__c=sysAdmin.Id);
		 insert leadContact;
	}
	static testmethod void testClassMeetingChatRest() {
	 System.runAs(sysAdmin) {
			
				ps_Term__c pTerm = mob_TestUtil.createNewTerm('T01', 'Test Term1');
			
				ps_Class__c pClass= mob_TestUtil.createClass(pTerm.Id, 'SFDC 401','Work', 'A11','A12', 'Workles', 'Field', 'ext11');
				ps_Class_Meeting__c  pClassMeeting= mob_TestUtil.createClassMeeting(pClass.Id, 'First Meeting', 1,'M21');
				ps_Enrollment__c pEnrollment = mob_TestUtil.createEnrollment(pClass.Id, 'EName', leadContact.Id);
				
				/*
				  create new FeedItem using the Get Rest Request
				*/
    			RestRequest req = new RestRequest(); 
				RestResponse res = new RestResponse();
		        
		        req.requestURI = 'https://aau--dev6.cs12.my.salesforce.com/services/apexrest/createClassMeetingChat';  
				req.httpMethod = 'GET';
				
				req.addParameter('classMeetingId',pClassMeeting.Id);
				req.addParameter('meetingNote','Test Feed Item rest Text');
				
				RestContext.request = req;
				RestContext.response = res;
				String feedMessage = mob_ClassMeeting_Save_ChatRest.saveMeetingChatterRecord();
				System.assertEquals(feedMessage,'Meeting chat record created');
		        
		        
		        /*
		           Insert Chatter feed exception coverage code 
		        */
		        
		     	req.addParameter('classMeetingId','Fake Id');
				req.addParameter('meetingNote','Test Feed Item rest Text');
			
				feedMessage = mob_ClassMeeting_Save_ChatRest.saveMeetingChatterRecord();
				System.assert(feedMessage.contains('Invalid id'));
				
				
		        /*
		          Rest Service get FeedItem method Call
		        */
		        req.requestURI = 'https://aau--dev6.cs12.my.salesforce.com/services/apexrest/classMeetingChat/'+pClassMeeting.Id;  
				req.httpMethod = 'GET';
				
				RestContext.request = req;
				RestContext.response = res;
				List<mob_ClassMeeting_ChatRest.ClassMeetingChat> classMeetingFeeds = mob_ClassMeeting_ChatRest.getClassMeetingChatters();
				System.assertEquals(classMeetingFeeds.size(),1);
				
				System.assertEquals(classMeetingFeeds.get(0).classMeetingId,pClassMeeting.Id);
				
				System.assertEquals(classMeetingFeeds.get(0).meetingNote,'Test Feed Item rest Text');
		}
	}

}