aau/sf_autobackup/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link Student User to their Contact to grab Class Schedule, etc.</description>
        <inlineHelpText>Link Student User to their Contact to grab Class Schedule, etc.</inlineHelpText>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

aau/sf_autobackup/objects/ps_Class__c.object
<CustomObject>
    <label>ps_Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Class_Meeting__c.object
<CustomObject>
    <label>ps_Class Meeting</label>
    <nameField>
        <label>Class Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Class Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Enrollment__c.object
<CustomObject>
    <label>ps_Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Term__c.object
<CustomObject>
    <label>ps_Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_ClassHistoryRest_Test.cls
@isTest
private class mob_ClassHistoryRest_Test {

  public static Contact leadContact;
  public static  User sysAdmin;
  public static  User aaUStudent;
  public static User aaUStudentUser;
  public static User aaUStudentUser1;
  static{
     sysAdmin = mob_TestUtil.makeUser('System Administrator');
       aaUStudent = mob_TestUtil.makeUser('AAU Student - Platform');
       aaUStudentUser = mob_TestUtil.makeUser('AAU Student - Platform');
       aaUStudentUser1 = mob_TestUtil.makeUser('AAU Student - Platform');
       //leadContact = new Contact(LastName = 'lName', FirstName = 'fName', Recruiting_Status__c = 'Applicant',student_user__c=sysAdmin.Id);
       leadContact = new Contact(LastName = 'lName', FirstName = 'fName',student_user__c=sysAdmin.Id);
    insert leadContact;
  }
  static testmethod void testHistoryRest() {
   System.runAs(sysAdmin) {
      
        Contact lead = mob_TestUtil.makeLead('Test', 'ContactShare');
        lead.student_user__c = aaUStudentUser.Id;
        update lead;
        
        //Create Contact Share record using Trigger 
        ContactShare conShare = [Select id,ContactId,UserorGroupId from ContactShare where contactId=:lead.Id and UserorGroupId =:aaUStudentUser.Id  and  rowCause='Manual' limit 1];
        System.assertEquals(lead.student_user__c,conShare.UserorGroupId);
        
        lead.student_user__c = aaUStudentUser1.Id;
        update lead;
        
        conShare = [Select id,ContactId,UserorGroupId from ContactShare where contactId=:lead.Id and UserorGroupId =:aaUStudentUser1.Id  and  rowCause='Manual' limit 1];
        System.assertEquals(aaUStudentUser1.Id,conShare.UserorGroupId);
        
        
        
        ps_Term__c pTerm = mob_TestUtil.createOldTerm('T01', 'Test Term1');
      
        ps_Class__c pClass= mob_TestUtil.createClass(pTerm.Id, 'SFDC 401','Work', 'A11','A12', 'Workles', 'Field', 'ext11');
        ps_Class_Meeting__c  pClassMeeting= mob_TestUtil.createOldClassMeeting(pClass.Id, 'First Meeting', 1,'M21');
        ps_Enrollment__c pEnrollment = mob_TestUtil.createEnrollment(pClass.Id, 'EName', leadContact.Id);
        system.debug('::Student User on Contact :: '+aaUStudentUser1.Id);
        
        
        RestRequest req = new RestRequest(); 
          RestResponse res = new RestResponse();
                req.addParameter('id',lead.id);
                // pass the req and resp objects to the method     
                //req.requestURI = 'https://aau--dev6.cs12.my.salesforce.com/services/apexrest/classHistory';  
                //req.httpMethod = 'GET';
          //mob_ClassHistoryRest.getEnrollments(req,res);
          mob_ClassHistoryRest.getEnrollments();
    }
  }
}