aau/sf_autobackup/objects/mob_Student__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Mobile Student App.</description>
    <fields>
        <fullName>Bus_Refresh_Rate__c</fullName>
        <description>Refresh Rate for Busses in milliseconds</description>
        <label>Bus Refresh Rate</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Teletrac_Account__c</fullName>
        <label>Teletrac Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teletrac_Password__c</fullName>
        <label>Teletrac Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teletrac_Username__c</fullName>
        <description>Used to connect to Teletrac REST Service to get Bus Location Info</description>
        <inlineHelpText>Used to connect to Teletrac REST Service to get Bus Location Info</inlineHelpText>
        <label>Teletrac Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>mob_Student</label>
</CustomObject>

aau/sf_autobackup/classes/mob_teletracInfoRest.cls
@RestResource(urlMapping='/teletracInfo/')

global with sharing class mob_teletracInfoRest {
  
  @HttpGet
  global static map<String,String> returnTeletracInfo() {
    map<String,String> teletracInfo = new map<String,String>();
    mob_Student__c mobSetting = mob_Student__c.getInstance();
    
    teletracInfo.put('Account', mobSetting.Teletrac_Account__c);
    teletracInfo.put('Username', mobSetting.Teletrac_Username__c);
    teletracInfo.put('Password', mobSetting.Teletrac_Password__c);
    teletracInfo.put('RefreshRate', String.valueOf(mobSetting.Bus_Refresh_Rate__c));
    teletracInfo.put('cacheTimeout', mobSetting.Cache_Timeout__c);
    
    return teletracInfo;
  }
}