aau/sf_autobackup/objects/Mobile_Links__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>We&apos;re only going to display the records marked Active in the Mobile Application</description>
        <inlineHelpText>We&apos;re only going to display the records marked Active in the Mobile Application</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <description>External Url to connect to from the Mobile App</description>
        <inlineHelpText>External Url to connect to from the Mobile App</inlineHelpText>
        <label>Url</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Link</label>
    <nameField>
        <label>Mobile Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_LinksREST_Test.cls
@isTest
private class mob_LinksREST_Test {

	static testmethod void testmobLinkRest() {
		Mobile_Links__c mobLink = new Mobile_Links__c();
		mobLink.name = 'Test Link 1';
		mobLink.Url__c = 'www.testLink1.com';
		mobLink.Active__c = true;
		insert mobLink;
		
		RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();
        // pass the req and resp objects to the method		 
        req.requestURI = 'https://aau--dev6.cs12.my.salesforce.com/services/apexrest/ExternalLinks';  
        req.httpMethod = 'GET';
		mob_LinksREST.getExternalLinks(req,res);
	}

}