aau/sf_autobackup/objects/Mobile_Links__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>We&apos;re only going to display the records marked Active in the Mobile Application</description>
        <inlineHelpText>We&apos;re only going to display the records marked Active in the Mobile Application</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>field to order links ni mobile app</description>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <description>External Url to connect to from the Mobile App</description>
        <inlineHelpText>External Url to connect to from the Mobile App</inlineHelpText>
        <label>Url</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Link</label>
    <nameField>
        <label>Mobile Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_LinksREST.cls
//
// Tim Pickard - Changed query to order by Order__c 8/20/2012
//
@RestResource(urlMapping='/ExternalLinks')
global with sharing class mob_LinksREST {
    
    @HttpGet
    global static List<ExtenralLink> getExternalLinks(RestRequest req, RestResponse res) {
        List<ExtenralLink> links = new List<ExtenralLink>();
        for(Mobile_Links__c link:[Select Name,Url__c from Mobile_Links__c where Active__c =:true ORDER BY Order__c NULLS LAST]){
            ExtenralLink elink = new ExtenralLink();
            elink.linkName = link.name;
            elink.linkUrl = link.Url__c;
            links.add(elink);
        }
        return links;
    }
    
    global class ExtenralLink{
        public String linkName{get;set;}
        public String linkUrl{get;set;}
    }

}