aau/sf_autobackup/objects/ps_Class__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_Nbr__c</fullName>
        <label>Catalog Nbr</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Section__c</fullName>
        <label>Class Section</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <label>Course Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <referenceTo>ps_Term__c</referenceTo>
        <relationshipName>Class_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ps_Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Class_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Class_Section__c</fullName>
        <label>Class Section</label>
        <referenceTo>ps_Class__c</referenceTo>
        <relationshipName>Class_Meeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Special_Topic__c</fullName>
        <label>Special Topic</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>ps_Class Meeting</label>
    <nameField>
        <label>Class Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Class Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class Section</label>
        <referenceTo>ps_Class__c</referenceTo>
        <relationshipLabel>ps_Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>xEnrollments</relationshipLabel>
        <relationshipName>xEnrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ps_Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

aau/sf_autobackup/objects/ps_Term__c.object
<CustomObject>
    <label>ps_Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ps_Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aau/sf_autobackup/classes/mob_StudentRest.cls
@RestResource(urlMapping='/classSchedule/*')
global with sharing class mob_StudentRest {

    @HttpGet
	global static PsEnrollments getEnrollments(RestRequest req, RestResponse res) {
		String contactId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
    	PsEnrollments psEnrlMents = new PsEnrollments();
		psEnrlMents.startDate = date.today();
		psEnrlMents.lastDate = date.today()+7;
		
		psEnrlMents.mobStudentsEnrolled = new Map<String,mobStudentEnrolled>();
		psEnrlMents.classMeetings = new Map<String,ClassMeeting>();
		 
		Set<Id> enrolledClasses = new Set<Id>();
		if(contactId!=null && contactId.startsWith('005')){
			for(ContactShare conShare :[Select contactid from ContactShare where UserOrGroupId =:contactId and rowcause='Manual']){
				contactId = conShare.ContactId;
			}
		}  
	    for(ps_Enrollment__c ps_Enrolmnt:[SELECT Id,Class_Section__c,Student__r.Id,Student__r.Name,Class_Section__r.Name,Class_Section__r.Course_Description__c,Class_Section__r.Catalog_Nbr__c, Class_Section__r.Term__c,Class_Section__r.Term__r.End_Date__c From ps_Enrollment__c 
	               where Student__c =: contactId AND Enrollment_Status__c = 'Enrolled' AND Class_Section__r.Term__r.End_Date__c > :date.today() ]){
	    	MobStudentEnrolled mobStdEnrolled = new MobStudentEnrolled();
	       	mobStdEnrolled.enrollmentId = ps_Enrolmnt.Id;
	       	mobStdEnrolled.studentId = ps_Enrolmnt.Student__r.Id;
	       	mobStdEnrolled.studentName = ps_Enrolmnt.Student__r.Name;
	       	mobStdEnrolled.className = ps_Enrolmnt.Class_Section__r.Name;
	       	mobStdEnrolled.classCatalogNbr = ps_Enrolmnt.Class_Section__r.Catalog_Nbr__c;
	       	mobStdEnrolled.classSectionId = ps_Enrolmnt.Class_Section__c;
	       	mobStdEnrolled.classDescription = ps_Enrolmnt.Class_Section__r.Course_Description__c;

		    enrolledClasses.add(ps_Enrolmnt.Class_Section__c);
	       	psEnrlMents.mobStudentsEnrolled.put(ps_Enrolmnt.Class_Section__c,mobStdEnrolled);
	    }
	    
	    if(!enrolledClasses.isEmpty()){
	    	for(ps_Class_Meeting__c psClassMeeting:[Select id,Class_Section__c,Wednesday__c, Tuesday__c, Thursday__c, Sunday__c, Start_Time__c, Start_Date__c, 
	                                                Special_Topic__c, Saturday__c, Name, Monday__c, Location__c, Friday__c, End_Time__c,
	                                                End_Date__c,Instructor_1__r.Name From ps_Class_Meeting__c where Class_Section__c in :enrolledClasses order by Start_Date__c
	                                                ]){
            	ClassMeeting clsMeeting = new ClassMeeting();
              	clsMeeting.classMeetingId =  psClassMeeting.id;
			  	clsMeeting.classSection =psClassMeeting.Class_Section__c;
			  	clsMeeting.isMonday = psClassMeeting.Monday__c;
			  	clsMeeting.isTuesday = psClassMeeting.Tuesday__c;
			  	clsMeeting.isWednesday = psClassMeeting.Wednesday__c;
			  	clsMeeting.isThursday = psClassMeeting.Thursday__c;
			  	clsMeeting.isFriday = psClassMeeting.Friday__c;
			  	clsMeeting.isSaturday = psClassMeeting.Saturday__c;
			  	clsMeeting.isSunday = psClassMeeting.Sunday__c;
			  	clsMeeting.startTime = psClassMeeting.Start_Time__c;
			  	clsMeeting.endTime = psClassMeeting.End_Time__c;
			  	clsMeeting.startDate = psClassMeeting.Start_Date__c;
			  	clsMeeting.endDate = psClassMeeting.End_Date__c;	
		      	clsMeeting.specialTopic = psClassMeeting.Special_Topic__c;
		      	clsMeeting.name = psClassMeeting.Name;
		      	clsMeeting.location = psClassMeeting.Location__c;
		      	clsMeeting.instructorName = psClassMeeting.Instructor_1__r.Name;
			  	psEnrlMents.classMeetings.put(psClassMeeting.Id,clsMeeting);     
	        }
	    }
	    return  psEnrlMents;
	}
	
	global class PsEnrollments{
	  	public Map<String,mobStudentEnrolled>	mobStudentsEnrolled {get;set;}
	  	public Map<String,ClassMeeting> classMeetings {get;set;}
	  	public Date startDate{get;set;}
	  	public Date lastDate{get;set;}
	}
	
	public class MobStudentEnrolled{
		String enrollmentId {get;set;}
	   	String studentId {get;set;}
	   	String studentName {get;set;}
	   	String className {get;set;}
	   	String classCatalogNbr {get;set;}
	   	String classSectionId {get;set;}
	   	String classDescription{get;set;}
	} 
	
	public class ClassMeeting{
		String  classMeetingId {get;set;}
	  	String  classSection {get;set;}
	  	boolean isMonday{get;set;}
	  	boolean isTuesday{get;set;}
	  	boolean isWednesday{get;set;}
	  	boolean isThursday{get;set;}
	  	boolean isFriday{get;set;}
	  	boolean isSaturday{get;set;}
	  	boolean isSunday{get;set;}
	  	String  startTime{get;set;}
	  	String  endTime{get;set;}
	  	Date    startDate{get;set;}
	  	Date    endDate{get;set;}	
      	String  specialTopic{get;set;}
      	String  name{get;set;}
      	String  location{get;set;}
      	String  instructorName{get;set;}
	}
}